version: "3"
name: pagopa-interop-probing
services:
  # Postgres DB
  postgres:
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    image: postgres:14@sha256:962ffbe9f6418387643411b127c1db27465e5a23b9a8849bfaf45fa6323963ce
    ports:
      - 6000:5432
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: -c 'max_connections=512' -c 'wal_level=logical'
    networks:
      - develop-network

  # Zookeeper for Kafka
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3@sha256:5b1354c4fa3bae600128eaa3ba9487ebd98b0aef40e3a39b32efe7533c8d2604
    networks:
      - develop-network

  # Kafka server
  kafka:
    image: quay.io/debezium/kafka:2.3@sha256:4009c39c2cc42686d1b5f0d2c46b3ff166e6ea98fb9a61d925b90f7fc56358e0
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    networks:
      - develop-network
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Web GUI for kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:53a6553765a806eda9905c43bfcfe09da6812035@sha256:7317d08c1d58f1c7e67adb936e3b181151bd5534a30b761f75fe8bddbf079ffd
    ports:
      - 8084:8080
    depends_on:
      - kafka
    networks:
      - develop-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  # ElasticMQ is a local SQS-compatible queue system, to replace AWS SQS in local development
  elasticmq:
    security_opt:
      - no-new-privileges:true
    image: softwaremill/elasticmq-native:1.5.7@sha256:0cb5bcc04638c80af1631e8cf5da9b96b9fb6f46a4164462231065dc516c102f
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq.local.conf:/opt/elasticmq.conf
    restart: always
    networks:
      - develop-network

  # InfluxDB â€” local instance
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root@root!
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - DOCKER_INFLUXDB_INIT_ORG=probing
      - DOCKER_INFLUXDB_INIT_BUCKET=probing-bucket
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    networks:
      - develop-network
    restart: unless-stopped

networks:
  develop-network:
    name: interop-probing-develop-network
    driver: bridge
